name: Build & Deploy Docs

on:
  push:
    branches: ["master", "github-actions"] # remove github-actions this after testing
  workflow_dispatch: # this makes the action manual

jobs:
  
  build:
    name: Install dependencies and generate static site
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      
      - name: Install vuepress
        run: yarn global add vuepress
      - name: Install package.json
        run: yarn
      - name: Build static site with vuepress
        # alias for vuepress build src defined in package.json
        run: yarn build
      
      - name: Write commit SHA to gitcommit.txt in dist
        shell: bash
        run: |
          echo $GITHUB_SHA > src/.vuepress/dist/gitcommit.txt
      
      - name: Get size of the dist folder
        shell: bash
        run: |
          du -ah src/.vuepress/dist

      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: vuepress-dist
          path: src/.vuepress/dist      

  deploy:
    name: Deploy to production
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout deployment keys
        uses: actions/checkout@v2

      - name: Download generated website dist dir
        uses: actions/download-artifact@v2
        with: 
          name: vuepress-dist
          path: src/.vuepress/dist

      - name: Check dist downloaded and check size
        shell: bash
        working-directory: src/.vuepress/
        run: |
          cat dist/gitcommit.txt
          du -ah dist
      
      - name: Decrypt deployment keys
        run: >
          openssl aes-256-cbc
          -K $encrypted_deaba444d90d_key
          -iv $encrypted_deaba444d90d_iv
          -in docs_deploy_key.enc
          -out ./docs_deploy_key
          -d
      - name: Run deployment script
        run: bash deploy.sh
