name: Build only

on:
  pull_request

jobs:
  build:
    name: Install dependencies and generate static site
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      
      - name: Install vuepress
        run: yarn global add vuepress
      - name: Install package.json
        run: yarn
      - name: Build static site with vuepress
        # alias for vuepress build src defined in package.json
        run: yarn build
      
      - name: Write commit SHA to gitcommit.txt in dist
        shell: bash
        run: |
          echo $GITHUB_SHA > src/.vuepress/dist/gitcommit.txt
      
      - name: Get size of the dist folder
        shell: bash
        run: |
          du -ah src/.vuepress/dist
      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: vuepress-dist
          path: src/.vuepress/dist
