name: Build & Deploy Docs

on:
  push:
    branches: ["master", "github-actions"] # remove github-actions this after testing
  workflow_dispatch: # this makes the action manual

jobs:
  
  build:
    name: Install dependencies and generate static site
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      
      - name: Install dependencies
      - run: yarn global add vuepress # install vuepress first
      - run: yarn # install package.json 
      - name: Build static site with vuepress
      - run: yarn build # alias for vuepress build src defined in package.json
      
      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: vuepress-dist
          path: src/.vuepress/dist
      
      - name: Write commit SHA to gitcommit.txt in dist
        shell: bash
        run: |
          echo $GITHUB_SHA > src/.vuepress/dist/gitcommit.txt
      
      - name: Get size of the dist folder
        shell: bash
          run: |
            du -ah src/.vuepress/dist
  
  deploy:
    name: Deploy to production
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download generated website dist dir
        uses: actions/download-artifact@v2
        with: 
          name: vuepress-dist
      
      - name: Check dist downloaded and check size
        shell: bash
        run: |
          cat dist/gitcommit.txt
          du -ah src/.vuepress/dist




